# This is a TOML document.

#the Broker config for start
brokerClusterName="DefaultCluster"
brokerName="broker-a"
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole="SYNC_MASTER"
flushDiskType="SYNC_FLUSH"
autoCreateTopicEnable=true

storePathRootDir="d:/iot/store"
brokerPort=10911
brokerIp="192.168.10.118"
#haMasterAddress="10.122.1.210:10912"